### ISSUE TITLE
Issue with unevaluatedProperties and allOf and arrays

### ISSUE THREAD

**Issue by silversurfer34** [python-jsonschema/jsonschema#1026]
I need to have a schema allowing extra fields only under one specific node (ExtensionProperties).
It works well using "additionalProperties": false with simple schemas:
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "rootppty": {
            "type": "string"
        },
        "ExtensionProperties": {
            "type": "object"          
        }
    }
}

```
This data is ok
```
{
  "rootppty": "ad",
   "ExtensionProperties": {
      "whatever": "you want"
    }
}
```
and this one fails validation as expected 
```
{
  "rootppty": "ok",
  "other": "fail",
   "ExtensionProperties": {
      "whatever": "you want"
    }
}
```

But when I have some allOf, I need to use "unevaluatedProperties": false as explained in the [documentation](https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties)
It works well with simple schemas
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "rootppty": {
            "type": "string"
        },
        "data": {
          "unevaluatedProperties": false,
          "allOf": [{
            "type": "object",
            "title": "IndividualProperties",
            "properties": {
              "Nestedppty": {
                "type": "string"
              }
            }
          }
         ]
        },
        "ExtensionProperties": {
            "type": "object"          
        }
    }
}
```
This data fails the validation as expected (on rootppty2 and Nestedppty2)
```
{
  "rootppty": "ok",
  "rootppty2": "fail",
  "data": {
    "Nestedppty": "ok",
    "Nestedppty2": "fail"
  },
   "ExtensionProperties": {
      "whatever": "you want"
    }
}
```

But when I am adding array in the allOf part I am facing issues
This schema does not fail validation on additional fields in the array
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "rootppty": {
            "type": "string"
        },
        "data": {
            "unevaluatedProperties": false,
            "allOf": [{
                    "type": "object",
                    "title": "IndividualProperties",
                    "properties": {
                        "Nestedppty": {
                            "type": "string"
                        },
                        "Nestedarray": {
                            "type": "array",
                            "items": {
                                "unevaluatedProperties": false,
                                "type": "object",
                                "properties": {
                                    "additionalProperties": false,
                                    "nestedarrayInternalpty": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
        "ExtensionProperties": {
            "type": "object"
        }
    }
}

```
for example this data should fail validation on nestedarrayInternalpty2
```
{
  "rootppty": "ok",
  "data": {
    "Nestedppty": "ok",
    "Nestedarray": [
      {"nestedarrayInternalpty": "ok"},
      {"nestedarrayInternalpty2": "should fail"}
    ]
  },
   "ExtensionProperties": {
      "whatever": "you want"
    }
}
```
but it fails also on Nestedppty, which should be ok
Am I doing something wrong or is there an issue when several "unevaluatedProperties": false are nested ?

**Comment by Julian** [comment]
(Even though this issue itself needs simplifying to be ready to look at) another example of `unevaluatedProperties` producing poor error messages is the simple schema (which I originally posted to #1074):

```python
from jsonschema import Draft202012Validator
schema = {
    "required": ["foo"],
    "unevaluatedProperties": False,
    "oneOf": [{"required": ["bar"]}],
}
Draft202012Validator(schema).validate({"foo": 37})
```

which produces the confusing:

```python
Traceback (most recent call last):
  File "/Users/julian/Desktop/uP.py", line 7, in <module>
    Draft202012Validator(schema).validate({"foo": 37})
  File "/Users/julian/Development/jsonschema/jsonschema/validators.py", line 424, in validate
    raise error
jsonschema.exceptions.ValidationError: Unevaluated properties are not allowed ('foo' was unexpected)

Failed validating 'unevaluatedProperties' in schema:
    {'oneOf': [{'required': ['bar']}],
     'required': ['foo'],
     'unevaluatedProperties': False}

On instance:
    {'foo': 37}
```

which can be especially bad if the `oneOf` (or applicator in general) produces some very deep error. Here it's probably `best_match` that needs enhancing to traverse into the applicators for this example.
