### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'read'

### ISSUE THREAD

**Issue by ahsanfarooqui** [python-jsonschema/jsonschema#1028]
Hello.

I just installed Anaconda package and tried to launch Jupyter notebook. The jsonschema is giving error regarding windows path in utils file. 

Kindly guide how to tackle this issue? I am using Python3.9

`(base) C:\Windows\system32>pip install jsonschema
Collecting jsonschema
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema) (21.4.0)
Installing collected packages: jsonschema
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 requires pyqt5<5.13, which is not installed.
spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.
conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible.
Successfully installed jsonschema-4.17.3

(base) C:\Windows\system32>jupyter notebook
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\ProgramData\Anaconda3\Lib\site-packages\notebook\notebookapp.py", line 79, in <module>
    from .services.contents.manager import ContentsManager
  File "C:\ProgramData\Anaconda3\Lib\site-packages\notebook\services\contents\manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbformat\__init__.py", line 11, in <module>
    from . import v1, v2, v3, v4
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbformat\v4\__init__.py", line 39, in <module>
    from .convert import downgrade, upgrade
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbformat\v4\convert.py", line 13, in <module>
    from .. import validator
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbformat\validator.py", line 15, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbformat\json_compat.py", line 11, in <module>
    import jsonschema
  File "C:\ProgramData\Anaconda3\Lib\site-packages\jsonschema\__init__.py", line 23, in <module>
    from jsonschema.validators import (
  File "C:\ProgramData\Anaconda3\Lib\site-packages\jsonschema\validators.py", line 432, in <module>
    meta_schema=_utils.load_schema("draft3"),
  File "C:\ProgramData\Anaconda3\Lib\site-packages\jsonschema\_utils.py", line 61, in load_schema
    data = path.read_text(encoding="utf-8")
AttributeError: 'WindowsPath' object has no attribute 'read_text'`

**Comment by Julian** [comment]
Hi -- I'm not sure what `jsonschema_utils` is, but it doesn't come from this package (or else I can't tell what's happening because of some formatting in your comment maybe?)

But yeah it seems unlikely that your issue is here, you may instead want the nbformat issue tracker but I'm not 100% sure.
