### ISSUE TITLE
custom validator iter_errors not resolving references

### ISSUE THREAD

**Issue by saifjarboui** [python-jsonschema/jsonschema#1093]
I created
` jsonschema.Draft202012Validator(schema, registry=registry)`
with 4 custom resources including signalItems.json and it is validating the json. 
But when I want to handle the errors as in [Documentation](https://python-jsonschema.readthedocs.io/en/latest/errors/#best-match-and-relevance).
It says that it cannot resolve the resources
val : is the validator that valiadtes data2 and I tested it with negative scenarios and returns ValidationError as expected.
I called `sorted(val.iter_errors(data2), key=str)`
I get this :

Traceback (most recent call last):
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 1055, in resolve_from_url
    document = self.store[url]
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_utils.py", line 20, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'signalItem.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 1058, in resolve_from_url
    document = self.resolve_remote(url)
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 1162, in resolve_remote
    with urlopen(uri) as url:
  File "C:\PythonFolders\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PythonFolders\Python39\lib\urllib\request.py", line 501, in open
    req = Request(fullurl, data)
  File "C:\PythonFolders\Python39\lib\urllib\request.py", line 320, in __init__
    self.full_url = url
  File "C:\PythonFolders\Python39\lib\urllib\request.py", line 346, in full_url
    self._parse()
  File "C:\PythonFolders\Python39\lib\urllib\request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'signalItem.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\saifeddine.jarboui\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\231.8109.197\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 331, in iter_errors
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 305, in properties
    yield from validator.descend(
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 305, in properties
    yield from validator.descend(
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 71, in items
    yield from validator.descend(
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 341, in anyOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 305, in properties
    yield from validator.descend(
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 71, in items
    yield from validator.descend(
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 376, in descend
    for error in errors:
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\_validators.py", line 284, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 421, in _validate_reference
    scope, resolved = resolve(ref)
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 1044, in resolve
    return url, self._remote_cache(url)
  File "C:\PythonFolders\Python39\lib\site-packages\jsonschema\validators.py", line 1060, in resolve_from_url
    raise exceptions._RefResolutionError(exc)
jsonschema.exceptions._RefResolutionError: unknown url type: 'signalItem.json
`

**Comment by Julian** [comment]
Hi there, please include a full example which reproduces your issue.

**Comment by saifjarboui** [comment]
I tried to reproduce after some time but it turns out that something happened ( I have no clue)
I will close this issue and reopen it if anything happens
