### ISSUE TITLE
Bug with $ref resolution in draft-07

### ISSUE THREAD

**Issue by DoubleBoba** [python-jsonschema/jsonschema#1108]
My schema:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "#masterdata/test_schema",
  "type": "object",
  "title": "Test schema",
  "properties": {
    "foo": {
      "$ref": "#/$defs/test_def"
    }
  },
  "$defs": {
    "test_def": {
        "$id": "#masterdata/test_def",
        "type": "object",
        "properties": {
            "locale": {
                "type": "string"
            },
            "value": {
                "type": "string"
            }
        }
    }
  }
}
```

Data that I'm trying to validate:

```json
{
  "foo": {
    "locale": "en",
    "value": "test string"
  }
}
```

Python code:

```python
import json

import jsonschema

with open('schema.json') as f:
    schema = json.load(f)

with open('data.json') as f:
    data = json.load(f)

jsonschema.validate(data, schema)
```

Expected behavior: data and schema are valid, so there shouldn't be any error.

Actual behavior:

```
Traceback (most recent call last):
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 909, in resolve_from_url
    document = self.store[url]
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/_utils.py", line 28, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 1018, in resolve_remote
    with urlopen(uri) as url:
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/***/PycharmProjects/jsonschema_bug/main.py", line 11, in <module>
    jsonschema.validate(data, schema)
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
  File "/Users/***/PycharmProjects/jsonschema_bug/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: unknown url type: ''
```

**Comment by Julian** [comment]
This already functions correctly in the 4.18 prerelease, which contains much improved referencing support. Feel free to install it, try it out and provide feedback.
