### ISSUE TITLE
hostname format checker might raise ValueError

### ISSUE THREAD

**Issue by jvtm** [python-jsonschema/jsonschema#1121]
At least on empty string `format: hostname` validator raises `ValueError` and not the expected `ValidationError`.

```
>>> from jsonschema.validators import validator_for
>>> schema = {"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "string", "format": "hostname"}
>>> vcls = validator_for(schema)
>>> validator = vcls(schema, format_checker=vcls.FORMAT_CHECKER)
>>> validator.validate("")
....
    for error in errors:
  File ".../jsonschema/_validators.py", line 238, in format
    validator.format_checker.check(instance, format)
  File ".../jsonschema/_format.py", line 135, in check
    result = func(instance)
             ^^^^^^^^^^^^^^
  File ".../jsonschema/_format.py", line 276, in is_host_name
    return FQDN(instance).is_valid
           ^^^^^^^^^^^^^^
  File ".../fqdn/__init__.py", line 44, in __init__
    raise ValueError("fqdn must be str")
ValueError: fqdn must be str
```

This also fails on `iter_errors()` usage.

This might be enough to fix it:
```diff
--- a/jsonschema/_format.py
+++ b/jsonschema/_format.py
@@ -270,6 +270,7 @@ with suppress(ImportError):
         draft7="hostname",
         draft201909="hostname",
         draft202012="hostname",
+        raises=ValueError,
     )
     def is_host_name(instance: object) -> bool:
         if not isinstance(instance, str):
```

Sorry, no time to properly test + send a PR at this point in time.

**Comment by Julian** [comment]
Thanks, indeed the first step here is to add a test to the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite). Help welcome whenever you care to.

**Comment by jvtm** [comment]
Discussion in https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/677 pointed out that _zero length strings_ are actually valid in the scope of given RFC's. So, my initial easy PR needs a bit more work.

As the zero length / empty string is valid, also `idn-hostname` fails in at least the following scenarios (using the underlying `idna` library for some quick checks):

```py
>>> import idna
>>> idna.encode("")
idna.core.IDNAError: Empty domain
```

```py
>>> idna.encode(".")
idna.core.IDNAError: Empty Label
```

To be continued...

**Comment by jvtm** [comment]
@Julian I think the easiest patch for now is to do a fast pre-check / `return True` on special cases on `jsonschema`, before calling the external libraries.

Something like
```py
if instance in ("", "."):
    return True
```

At the moment `idna` raises exceptions on those too legit cases, and `fqdn` gives out the `ValueError`.

Even with that fix I think it makes sense to add `raises=ValueError` to the `hostname` / `fqdn` check.

:thinking:

**Comment by Julian** [comment]
> I think the easiest patch for now is to do a fast pre-check

Yep that seems right to me.

> Even with that fix I think it makes sense to add raises=ValueError to the hostname / fqdn check.

I'm somewhat OK with this but can you try to read through the source code of those libs and see whether there appear to be any explicit code paths which will really hit that? As I say I'm probably OK adding it regardless, but it's a bit nice to be thorough while we're here.

**Comment by jvtm** [comment]
And then there is the Python standard lib `idna` encoding... oh my :exploding_head: 

```
>>> "hello".encode("idna")
b'hello'

>>> "hello.".encode("idna")
b'hello.'

>>> "".encode("idna")
b''

>>> ".".encode("idna")
Traceback (most recent call last):
  File "lib/python3.11/encodings/idna.py", line 163, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

I need a short break from all this... maybe resuming tomorrow.

**Comment by shane-kearns** [comment]
I have encountered this regression when upgrading from 3.0.1 to 4.21.1 (a big jump as older versions don't support python 3.12)
Where the schema includes:
```
"address": {
    "type": "string",
    "anyOf": [
        {
            "format": "hostname"
        },
        {
            "format": "ipv4"
        },
        {
            "format": "ipv6"
        }
    ]
},
```

Previously passing an empty string would have resulted in a 'format' error, it now leaks the ValueError exception instead of being able to enumerate all the errors in the document being validated.

```
    errors = list(self.VALIDATOR.iter_errors(spec))
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:371: in iter_errors
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:296: in properties
    yield from validator.descend(
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:419: in descend
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:296: in properties
    yield from validator.descend(
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:419: in descend
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:296: in properties
    yield from validator.descend(
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:419: in descend
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:296: in properties
    yield from validator.descend(
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:419: in descend
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:340: in anyOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
tests\.virtualenv\Lib\site-packages\jsonschema\validators.py:419: in descend
    for error in errors:
tests\.virtualenv\Lib\site-packages\jsonschema\_keywords.py:226: in format
    validator.format_checker.check(instance, format)
tests\.virtualenv\Lib\site-packages\jsonschema\_format.py:137: in check
    result = func(instance)
tests\.virtualenv\Lib\site-packages\jsonschema\_format.py:277: in is_host_name
    return FQDN(instance, min_labels=1).is_valid
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _


    def __init__(self, fqdn, *nothing, **kwargs):
        if nothing:
            raise ValueError("got extra positional parameter, try kwargs")
        unknown_kwargs = set(kwargs.keys()) - {"allow_underscores", "min_labels"}
        if unknown_kwargs:
            raise ValueError("got extra kwargs: {}".format(unknown_kwargs))

        if not (fqdn and isinstance(fqdn, str)):
>           raise ValueError("fqdn must be str")
E           ValueError: fqdn must be str
```

I've written a longer comment on the tests as to what I think the behaviour should be, but not "crashing" (leaking exceptions) when enumerating errors would be a good start here.

**Comment by shane-kearns** [comment]
I believe that https://github.com/ypcrts/fqdn/issues/45 is the root cause, but catching a ValueError defensively here is probably the right thing to do.

**Comment by Julian** [comment]
Thanks for filing that. Yeah I'm happy with catching the `ValueError` in the interim (but I'd wait till the test is merged upstream).

**Comment by sirosen** [comment]
I accidentally pushed a commit which I worked up to resolve this to the wrong place and it closed this (smart-commit). 🤦 

Sorry about the noise.

**Comment by sirosen** [comment]
I've been slowly working through cleanup. I think the situation is that after a short chat with Julian, we're keeping https://github.com/python-jsonschema/jsonschema/commit/51506b97291adac6e3ca926442eb07f787bc98b5 in `main`. So this is actually resolved and will be fixed in the next release!

Separately, we've got (really, Julian has!) some syncing going on between the official testsuite and this repo.

I'm re-marking this resolved, since we aren't backing out the change! 🎉
