### ISSUE TITLE
SchemaError on patterns

### ISSUE THREAD

**Issue by DenizUgur** [python-jsonschema/jsonschema#1129]
The following JSON and its schema were tested on a different online [tool](https://www.jsonschemavalidator.net) and there is no validation issues. However, jsonschema fails to validate my regex. Is there an issue on my end or this is a bug with this package?

<details><summary>Test JSON</summary>
<p>

```json
{
  "test": "file.meta"
}
```

</p>
</details> 

<details><summary>Schema</summary>
<p>

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "properties": {
    "test": {
      "type": "string",
      "pattern": "^file(?>\\.[a-z]{4})+$"
    }
  }
}
```

</p>
</details> 

<details><summary>Python log</summary>
<p>

```python
>>> import jsonschema
>>> import json
>>> s = open("schema.json", "r")
>>> js = json.load(s)
>>> t = open("test.json", "r")
>>> jt = json.load(t)
>>> jsonschema.validate(instance=jt, schema=js)
Traceback (most recent call last):
  File "/Users/deniz/Library/Python/3.9/lib/python/site-packages/jsonschema/_format.py", line 137, in check
    result = func(instance)
  File "/Users/deniz/Library/Python/3.9/lib/python/site-packages/jsonschema/_format.py", line 388, in is_regex
    return bool(re.compile(instance))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/sre_parse.py", line 823, in _parse
    raise source.error("unknown extension ?" + char,
re.error: unknown extension ?> at position 6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deniz/Library/Python/3.9/lib/python/site-packages/jsonschema/validators.py", line 1298, in validate
    cls.check_schema(schema)
  File "/Users/deniz/Library/Python/3.9/lib/python/site-packages/jsonschema/validators.py", line 297, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: '^file(?>\\.[a-z]{4})+$' is not a 'regex'

Failed validating 'format' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][3]['properties']['pattern']:
    {'format': 'regex', 'type': 'string'}

On schema['properties']['test']['pattern']:
    '^file(?>\\.[a-z]{4})+$'
>>>
```

</p>
</details>

**Comment by DenizUgur** [comment]
[Had](https://docs.python.org/3/library/re.html) to use Python 3.11 (duh!)
