### ISSUE TITLE
[version `>=4.18`] AttributeError: 'str' object has no attribute 'get' or TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by jslorrma** [python-jsonschema/jsonschema#1140]
In one of my python projects I'm using `jsonschema` and with package versions `>=4.18` I get errors during import of `jsonschema`, like e.g.:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
...\test.py in line 18
     75             return _collections_abc._check_methods(C, "__len__", "__iter__", "__contains__")
     76         return NotImplemented
---> 78 import jsonschema

File ...\lib\site-packages\jsonschema\__init__.py:17
     15 from jsonschema.exceptions import SchemaError, ValidationError
     16 from jsonschema.protocols import Validator
---> 17 from jsonschema.validators import (
     18     Draft3Validator,
     19     Draft4Validator,
     20     Draft6Validator,
     21     Draft7Validator,
     22     Draft201909Validator,
     23     Draft202012Validator,
     24     validate,
     25 )
     28 def __getattr__(name):
     29     if name == "__version__":

File ...\lib\site-packages\jsonschema\validators.py:19
     16 import warnings
     18 from attrs import define, field, fields
---> 19 from jsonschema_specifications import REGISTRY as SPECIFICATIONS
     20 from rpds import HashTrieMap
     21 import referencing.exceptions

File ...\lib\site-packages\jsonschema_specifications\__init__.py:11
      7 from jsonschema_specifications._core import _schemas
      9 #: A `referencing.jsonschema.SchemaRegistry` containing all of the official
     10 #: meta-schemas and vocabularies.
---> 11 REGISTRY: _SchemaRegistry = (_schemas() @ _Registry()).crawl()
     13 __all__ = ["REGISTRY"]

File ...\lib\site-packages\referencing\_core.py:410, in Registry.crawl(self)
    407 while uncrawled:
    408     uri, resource = uncrawled.pop()
--> 410     id = resource.id()
    411     if id is not None:
    412         uri = urljoin(uri, id)

File ...\lib\site-packages\referencing\_core.py:145, in Resource.id(self)
    141 def id(self) -> URI | None:
    142     """
    143     Retrieve this resource's (specification-specific) identifier.
    144     """
--> 145     id = self._specification.id_of(self.contents)
    146     if id is None:
    147         return

File ...\lib\site-packages\referencing\jsonschema.py:39, in _dollar_id(contents)
     37 if isinstance(contents, bool):
     38     return
---> 39 return contents.get("$id")

AttributeError: 'str' object has no attribute 'get'
```

or 
```python
Traceback (most recent call last):
  File ...\test1.py", line 11, in <module>
    import jsonschema
  File "...\lib\site-packages\jsonschema\__init__.py", line 17, in <module>
    from jsonschema.validators import (
  File "...\lib\site-packages\jsonschema\validators.py", line 19, in <module>
    from jsonschema_specifications import REGISTRY as SPECIFICATIONS
  File "...\lib\site-packages\jsonschema_specifications\__init__.py", line 11, in <module>
    REGISTRY: _SchemaRegistry = (_schemas() @ _Registry()).crawl()
  File "...\lib\site-packages\referencing\_core.py", line 416, in crawl
    uncrawled.extend((uri, each) for each in resource.subresources())
  File "...\lib\site-packages\referencing\_core.py", line 416, in <genexpr>
    uncrawled.extend((uri, each) for each in resource.subresources())
  File "...\lib\site-packages\referencing\_core.py", line 154, in <genexpr>
    return (
  File ...\lib\site-packages\referencing\jsonschema.py", line 181, in subresources_of
    yield from items
TypeError: 'bool' object is not iterable
```

Debugging and tracing back the error, I found out that the cause of this error has something to do with the definition of a custom Python class that I have defined and use in my project. 

I don't get this error with `jsonschema < 4.18`.

## How to reproduce
 The following code examples can be used to reproduce the error

**Example 1:** 
(this one randomly produces the `AttributeError` or the `TypeError`)
```python
from __future__ import annotations
from collections.abc import Sequence  
  
class NonStringSequence(Sequence):  
    """
    A custom Sequence class that only considers non-string iterables as its subclasses.
    """
    @classmethod
    def __subclasshook__(cls, C):
        return cls is NonStringSequence1 and not issubclass(C, str | bytes)

import jsonschema
```

**Example 2:**
```python
from __future__ import annotations
from collections.abc import Sequence  
import _collections_abc
  
class NonStringSequence(Sequence):  
    """
    A custom Sequence class that only considers non-string iterables as its subclasses.
    """
    @classmethod
    def __subclasshook__(cls, C):
        if cls is NonStringSequence and not issubclass(C, str | bytes):
            return _collections_abc._check_methods(C, "__len__", "__iter__", "__contains__")
        return NotImplemented

import jsonschema
```

## Environment

**`environment.yaml`:**
```yaml
name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - jsonschema[version='>=4.18']
```

**`conda list`:**
```yaml
# packages in environment env:
#
# Name                    Version                   Build  Channel
attrs                     23.1.0             pyh71513ae_1    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
jsonschema                4.18.4             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
openssl                   3.1.1                hcfcfb64_1    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
python                    3.11.4          h2628c8c_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
referencing               0.30.0             pyhd8ed1ab_0    conda-forge
rpds-py                   0.9.2           py311hc37eb10_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.41.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
```

**Comment by Julian** [comment]
Hey.

Those look like broken subclasses to me (both of them essentially) -- specifically, `jsonschema` aside (and sticking to your first example for simplicity), that code would cause:

```python
from __future__ import annotations
from collections.abc import Sequence  
class NonStringSequence(Sequence):  
    @classmethod
    def __subclasshook__(cls, C):
        return cls is NonStringSequence and not issubclass(C, str | bytes)
print(issubclass(dict, Sequence))
```

which is what's happening while importing `jsonschema`, which needs essentially to check whether something is a sequence or not.

`dict`s are indeed not sequences in Python.

I'm not sure if your real code suffers from the same issue, feel free to share if so, but as-is I don't think I'd want to change anything to make this work -- I suspect a great number of things might silently break if you introduce such a `__subclasshook__` -- you're essentially making a ton of classes which are not sequences claim to be sequences.

**Comment by jslorrma** [comment]
> Hey.
> 
> Those look like broken subclasses to me (both of them essentially) -- specifically, `jsonschema` aside (and sticking to your first example for simplicity), that code would cause:
> 
> ```python
> from __future__ import annotations
> from collections.abc import Sequence  
> class NonStringSequence(Sequence):  
>     @classmethod
>     def __subclasshook__(cls, C):
>         return cls is NonStringSequence and not issubclass(C, str | bytes)
> print(issubclass(dict, Sequence))
> ```
> 
> to return `True`, i.e. to claim that `dict` is a `collection.abc.Sequence`.
> 
> That's also what's happening while importing `jsonschema`, which needs essentially to check whether something is a sequence or not.
> 
> `dict`s are indeed not sequences in Python.
> 
> I'm not sure if your real code suffers from the same issue, feel free to share if so, but as-is I don't think I'd want to change anything to make this work -- I suspect a great number of things might silently break if you introduce such a `__subclasshook__` -- you're essentially making a ton of classes which are not sequences claim to be sequences.

Thanks for the quick reply :-)

You're absolutely right the class implementation or better the implementation of the `__subclasshook__` is wrong and 'dangerous'. The error I get when importing `jsonschema` is just the first breaking this causes (anyhow strange that version `4.17.3` does cause the breaking). 

Due to writing this issue and with your feedback I have now fixed the implementation of my two subclasses, like:

```python
class NonStringSequence(metaclass=ABCMeta):
    """
    A custom Sequence class that only considers non-string iterables as its subclasses.
    """

    __slots__ = ()

    @classmethod
    def __subclasshook__(cls, C):
        if cls is NonStringSequence and issubclass(C, Sequence) and not issubclass(C, str | bytes):
            return True
        return NotImplemented


class NonStringIterable(metaclass=ABCMeta):
    """
    A custom Iterable class that only considers non-string iterables as its subclasses.
    """
    __slots__ = ()

    @classmethod
    def __subclasshook__(cls, C):
        if cls is NonStringIterable and issubclass(C, Iterable) and not issubclass(C, str | bytes):
            return True
        return NotImplemented
```

This implentation behaves like expected and does not break `jsonschema` import:
```python
>>> import array
... 
>>> for _type in (int, float, bool, str, bytes, list, set, tuple, dict, array.array):
...     print(f"issubclass({_type}, Iterable):", issubclass(_type, Iterable))
...     print(f"issubclass({_type}, Sequence):" ,issubclass(_type, Sequence))
...     print(f"issubclass({_type}, NonStringIterable):", issubclass(_type, NonStringIterable))
...     print(f"issubclass({_type}, NonStringSequence):", issubclass(_type, NonStringSequence))
...     print()
issubclass(<class 'int'>, Iterable): False
issubclass(<class 'int'>, Sequence): False
issubclass(<class 'int'>, NonStringIterable): False
issubclass(<class 'int'>, NonStringSequence): False

issubclass(<class 'float'>, Iterable): False
issubclass(<class 'float'>, Sequence): False
issubclass(<class 'float'>, NonStringIterable): False
issubclass(<class 'float'>, NonStringSequence): False

issubclass(<class 'bool'>, Iterable): False
issubclass(<class 'bool'>, Sequence): False
issubclass(<class 'bool'>, NonStringIterable): False
issubclass(<class 'bool'>, NonStringSequence): False

issubclass(<class 'str'>, Iterable): True
issubclass(<class 'str'>, Sequence): True
issubclass(<class 'str'>, NonStringIterable): False
issubclass(<class 'str'>, NonStringSequence): False

issubclass(<class 'bytes'>, Iterable): True
issubclass(<class 'bytes'>, Sequence): True
issubclass(<class 'bytes'>, NonStringIterable): False
issubclass(<class 'bytes'>, NonStringSequence): False

issubclass(<class 'list'>, Iterable): True
issubclass(<class 'list'>, Sequence): True
issubclass(<class 'list'>, NonStringIterable): True
issubclass(<class 'list'>, NonStringSequence): True

issubclass(<class 'set'>, Iterable): True
issubclass(<class 'set'>, Sequence): False
issubclass(<class 'set'>, NonStringIterable): True
issubclass(<class 'set'>, NonStringSequence): False

issubclass(<class 'tuple'>, Iterable): True
issubclass(<class 'tuple'>, Sequence): True
issubclass(<class 'tuple'>, NonStringIterable): True
issubclass(<class 'tuple'>, NonStringSequence): True

issubclass(<class 'dict'>, Iterable): True
issubclass(<class 'dict'>, Sequence): False
issubclass(<class 'dict'>, NonStringIterable): True
issubclass(<class 'dict'>, NonStringSequence): False

issubclass(<class 'array.array'>, Iterable): True
issubclass(<class 'array.array'>, Sequence): True
issubclass(<class 'array.array'>, NonStringIterable): True
issubclass(<class 'array.array'>, NonStringSequence): True
```


Thanks again ...

**Comment by Julian** [comment]
Great, glad to hear it!
