### ISSUE TITLE
additionalItems can blow up when rendering a message for a non-homogeneous array

### ISSUE THREAD

**Issue by michaelmior** [python-jsonschema/jsonschema#1157]
The [`extras_msg` function](https://github.com/python-jsonschema/jsonschema/blob/ccfbc8c32ddcd0e6a13a30371e5a9b1f2036c0ba/jsonschema/_utils.py#L88-L94) sometimes throws an exception when everything in extras is not the same type because sorting fails.

Assuming the specific sort order is not terribly important, changing from

```python
        return ", ".join(repr(extra) for extra in sorted(extras)), verb
```

to

```python
        return ", ".join(extra for extra in sorted(map(repr, extras))), verb
```

should solve the problem.

**Comment by Julian** [comment]
Hi. Thanks. Can you include a full reproducing example?

**Comment by michaelmior** [comment]
Unfortunately this was part of a larger job that failed and I didn't catch the specific input. I do however have a stack trace.

```
Traceback (most recent call last):
  File "/home/mmior/apps/json-fetcher/download.py", line 57, in <module>
    jsonschema.validate(instance=doc_obj, schema=schema)
  File "/home/mmior/.local/share/virtualenvs/json-fetcher-ZSn11VnQ/lib/python3.9/site-packages/jsonschema/validators.py", line 1305, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/home/mmior/.local/share/virtualenvs/json-fetcher-ZSn11VnQ/lib/python3.9/site-packages/jsonschema/exceptions.py", line 444, in best_match
    best = next(errors, None)
  File "/home/mmior/.local/share/virtualenvs/json-fetcher-ZSn11VnQ/lib/python3.9/site-packages/jsonschema/validators.py", line 368, in iter_errors
    for error in errors:
  File "/home/mmior/.local/share/virtualenvs/json-fetcher-ZSn11VnQ/lib/python3.9/site-packages/jsonschema/_validators.py", line 57, in additionalProperties
    yield ValidationError(error % extras_msg(extras))
  File "/home/mmior/.local/share/virtualenvs/json-fetcher-ZSn11VnQ/lib/python3.9/site-packages/jsonschema/_utils.py", line 94, in extras_msg
    return ", ".join(repr(extra) for extra in sorted(extras)), verb
TypeError: '<' not supported between instances of 'str' and 'bool'
```

**Comment by davidrios** [comment]
I have the same issue.

Here's a minimal schema for reproduction:

```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "array_multiple_types": {
      "oneOf": [
        {
          "type": "array",
          "items": [
            {
              "const": "test1"
            }
          ],
          "additionalItems": false,
          "minItems": 1
        },
        {
          "type": "array",
          "items": [
            {
              "const": "test2"
            },
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ],
          "additionalItems": false,
          "minItems": 3
        }
      ]
    }
  }
}
```

and an instance to be validated:

```json
{
  "array_multiple_types": [
    "test2",
    "aaa",
    99
  ]
}
```

I can confirm the proposed solutions does fix the problem.

Thanks for the project BTW!

**Comment by Julian** [comment]
Thanks, that helps!
