### ISSUE TITLE
Invalid data type is ignored

### ISSUE THREAD

**Issue by Fritzforcode** [python-jsonschema/jsonschema#1317]
I strictly assigned the "type" field of a schema to "object". Then i called jsonschema.validate with a python set as instance. I got no error. Should this not raise an error?

**Comment by Julian** [comment]
You'll have to be more specific.

```
⊙  ~[jsonschema:python] -c 'from jsonschema import validate; validate({1, 2, 3}, {"type": "object"})'                                                                                                                                                                                                               
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/jsonschema/lib/python3.12/site-packages/jsonschema/validators.py", line 1308, in validate
    raise error
jsonschema.exceptions.ValidationError: {1, 2, 3} is not of type 'object'

Failed validating 'type' in schema:
    {'type': 'object'}

On instance:
    {1, 2, 3}
```
