### ISSUE TITLE
"multipleOf" validation is done with faulty float math

### ISSUE THREAD

**Issue by GenosW** [python-jsonschema/jsonschema#951]
The logic for the multipleOf validator is flawed:

```python
>>> schema = {"type": "number", "multipleOf": 0.2}
>>> jsonschema.validate(0.8, schema=schema)
>>> jsonschema.validate(1.2, schema=schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: 1.2 is not a multiple of 0.2

Failed validating 'multipleOf' in schema:
    {'multipleOf': 0.2, 'type': 'number'}

On instance:
    1.2
```

The issue is how the check is implemented:
```python
def multipleOf(validator, dB, instance, schema):
    if not validator.is_type(instance, "number"):
        return

    if isinstance(dB, float):
        quotient = instance / dB # 1.2 / 0.2 = 5.999999999
        try:
            failed = int(quotient) != quotient # int(5.999999999 ) = 5 --> Problem
      ...
```

First, the int(quotient) simply "cuts away all number after the comma" --> round(quotient) is what you want.
Secondly, comparison between floats should not be done with strict checks like that.
Use the math.isclose() function instead which checks with tolerances.

In total:
```python
def multipleOf(validator, dB, instance, schema):
    if not validator.is_type(instance, "number"):
        return

    if isinstance(dB, float):
        quotient = instance / dB
        try:
            failed = math.isclose(round(quotient), quotient) # CORRECT!
      ...
```

**Comment by Julian** [comment]
Hi. Feel free to look at one of the previous tickets on this. `math.isclose` is for when there's a reasonable tolerance to use.
